/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinicpms.view.type.export_progress_view;

import clinicpms.controller.EntityDescriptor;
import clinicpms.view.View;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyVetoException;
import javax.swing.JInternalFrame;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;

/**
 *
 * @author colin
 */
public class ExportProgressView extends View {
    enum Mode {PATIENT, APPOINTMENT, NONE};
    private Mode mode = Mode.NONE;
    private ActionListener myController = null;
    private EntityDescriptor entityDescriptor = null;
    private InternalFrameAdapter internalFrameAdapter = null;
    private View.Viewer myViewType = null;
    
    
    private void setMode(Mode value){
        mode = value;
    }
    
    private Mode getMode(){
        return mode;
    }
    
    private void setMyViewType(View.Viewer value){
        this.myViewType = value;
    }
    
    private ActionListener getMyController(){
         return this.myController;
     }
    private void setMyController(ActionListener value){
        this.myController = value;
    }
    
    private void setEntityDescriptor(EntityDescriptor value){
        this.entityDescriptor = value;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barPatients = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        barAppointments = new javax.swing.JProgressBar();
        btnStart = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setTitle("Exported data progress");

        barPatients.setMinimum(0);
        barPatients.setStringPainted(true);

        barPatients.setMaximum(100);

        jLabel1.setText("Patients");

        jLabel2.setText("Appointments");

        barAppointments.setMinimum(0);
        barAppointments.setMaximum(100);
        barAppointments.setStringPainted(true);

        btnStart.setText("Start export");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnClose.setText("Close view");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(barPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(barAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnStart)
                        .addGap(24, 24, 24)
                        .addComponent(btnClose)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(btnClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        try{
            setClosed(true);
        }catch (PropertyVetoException ex){
            
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        ActionEvent actionEvent = new ActionEvent(this, 
                ActionEvent.ACTION_PERFORMED,
                EntityDescriptor.ExportProgressViewControllerActionEvent.EXPORT_START_REQUEST.toString());
        this.getMyController().actionPerformed(actionEvent);
        
    }//GEN-LAST:event_btnStartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barAppointments;
    private javax.swing.JProgressBar barPatients;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    
    
    private void centreViewOnDesktop(Container desktopView, JInternalFrame view){
        Insets insets = desktopView.getInsets();
        Dimension deskTopViewDimension = desktopView.getSize();
        Dimension myViewDimension = view.getSize();
        view.setLocation(new Point(
                (int)(deskTopViewDimension.getWidth() - (myViewDimension.getWidth()))/2,
                (int)((deskTopViewDimension.getHeight()-insets.top) - myViewDimension.getHeight())/2));
    }
    /**
     * Creates new form MigrationManagerModelViewer
     */
    public ExportProgressView(View.Viewer myViewType,ActionListener myController,
            EntityDescriptor entityDescriptor) {
        setMyViewType(myViewType);
        setEntityDescriptor(entityDescriptor);
        setMyController(myController);
        initComponents();
 
        this.initialiseView();

    }
    
    @Override
    public void addInternalFrameClosingListener(){
        /**
         * Establish an InternalFrameListener for when the view is closed 
         */
        
        internalFrameAdapter = new InternalFrameAdapter(){
            @Override  
            public void internalFrameClosing(InternalFrameEvent e) {
                ActionEvent actionEvent = new ActionEvent(
                        ExportProgressView.this,ActionEvent.ACTION_PERFORMED,
                        EntityDescriptor.ExportProgressViewControllerActionEvent.EXPORT_PROGRESS_CLOSE_NOTIFICATION.toString());
                getMyController().actionPerformed(actionEvent);
            }
        };
        this.addInternalFrameListener(internalFrameAdapter);
    }

    @Override
    public void initialiseView(){
        this.setVisible(true);
        
        
    }
    
    @Override 
    public EntityDescriptor getEntityDescriptor(){
        return entityDescriptor;   
    }
    
    @Override
    public View.Viewer getMyViewType(){
        return this.myViewType;
    }
    
    @Override
    public void propertyChange(PropertyChangeEvent e){
        ActionEvent actionEvent = null;
        EntityDescriptor.ExportProgressViewControllerPropertyChangeEvent propertyName =
                EntityDescriptor.ExportProgressViewControllerPropertyChangeEvent.valueOf(e.getPropertyName());
        
        switch (propertyName){
            case progress:{
                int progress = (Integer) e.getNewValue();
                switch (getMode()){
                    case PATIENT:
                        barPatients.setIndeterminate(false);
                        barPatients.setValue(progress);
                        break;
                    case APPOINTMENT:
                        barAppointments.setIndeterminate(false);
                        barAppointments.setValue(progress);
                        break;
                }
                break;
            }
            case EXPORT_COMPLETED:
                btnStart.setEnabled(true);
                setMode(Mode.NONE);
                break;
                
            case PREPARE_FOR_RECEIPT_OF_APPOINTMENT_PROGRESS:
                barAppointments.setIndeterminate(true);
                setMode(Mode.APPOINTMENT);
                actionEvent = new ActionEvent(
                        ExportProgressView.this,ActionEvent.ACTION_PERFORMED,
                        EntityDescriptor.ExportProgressViewControllerActionEvent.READY_FOR_RECEIPT_OF_APPOINTMENT_PROGRESS.toString());
                getMyController().actionPerformed(actionEvent);
                break;
                
            case PREPARE_FOR_RECEIPT_OF_PATIENT_PROGRESS:
                barPatients.setIndeterminate(true);
                setMode(Mode.PATIENT);
                actionEvent = new ActionEvent(
                        ExportProgressView.this,ActionEvent.ACTION_PERFORMED,
                        EntityDescriptor.ExportProgressViewControllerActionEvent.READY_FOR_RECEIPT_OF_PATIENT_PROGRESS.toString());
                getMyController().actionPerformed(actionEvent);
                break;
        }


    }

}
